### ISSUE TITLE
Mainline LIMA driver

### ISSUE THREAD

**Issue by MaHoef** [ikwzm/ZynqMP-FPGA-Ubuntu20.04-Lima-Ultra96#1]
Hello,
interesting work you did to get rid of the propriety MALI drivers.
I have recently used the 5.10.26 mainline Kernel on the Ultra96v2.
There are some improvements of the LIMA driver:
https://github.com/gregkh/linux/commits/linux-5.10.y/drivers/gpu/drm/lima
However, I didn't manage yet to get the LIMA driver up and running yet.
If you are interested in a co-collaboration I can send you the PetaLinux 2020.2 project for the Ultra96v2.
It contains already the yocto recipes to pull the 5.10.26 kernel.
Regards
Marco

**Comment by ikwzm** [comment]
Thank you for your valuable feedback.

**Comment by MaHoef** [comment]
Was just a comment not an issue
